# Generated by Django 5.1.3 on 2025-03-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_worddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarformmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
