# Generated by Django 5.1.4 on 2025-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_seminarformmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarformmodel',
            name='verification_id',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
