# Generated by Django 5.1.3 on 2025-05-07 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_seminarformmodel_verification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarformmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarformmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
